/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anurag
 */

import TestDAO.StudentRegDAO;
import java.sql.ResultSet;
public class TestApplicationForm extends javax.swing.JFrame {

    /**
     * Creates new form TestApplicationForm
     */
    ResultSet rs = null;
    public TestApplicationForm() {
        initComponents();
        setSize(600,600);
        StudentRegDAO data = new StudentRegDAO();
        rs = data.getAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sname = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        sadd = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        unm = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        getContentPane().add(sname);
        sname.setBounds(280, 30, 240, 40);

        mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobActionPerformed(evt);
            }
        });
        getContentPane().add(mob);
        mob.setBounds(280, 180, 240, 45);
        getContentPane().add(sadd);
        sadd.setBounds(280, 100, 240, 45);
        getContentPane().add(branch);
        branch.setBounds(280, 260, 240, 44);
        getContentPane().add(unm);
        unm.setBounds(280, 340, 240, 44);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(230, 460, 112, 35);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 340, 120, 40);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 30, 120, 40);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 100, 120, 40);

        jLabel4.setText("Mobile ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 180, 120, 40);

        jLabel5.setText("Branch");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 260, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        try{
            if(rs.next()){
                sname.setText(rs.getString(2));
                mob.setText(rs.getInt(4) + "");
                branch.setText(rs.getString(5));
                unm.setText(rs.getString(6));
                sadd.setText(rs.getString(3));
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mob;
    private javax.swing.JButton next;
    private javax.swing.JTextField sadd;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField unm;
    // End of variables declaration//GEN-END:variables
}