/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anurag
 */

import TestDAO.StudentRegDAO;
import TestDTO.StudentRegDTO;
import java.sql.ResultSet;
public class TestApplicationInsertForm extends javax.swing.JFrame {

    ResultSet rs = null;
    /**
     * Creates new form TestApplicationInsertForm
     */
    public TestApplicationInsertForm() {
        initComponents();
        setSize(600,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sname = new javax.swing.JTextField();
        sadd = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(sname);
        sname.setBounds(370, 80, 140, 30);
        getContentPane().add(sadd);
        sadd.setBounds(370, 140, 140, 30);
        getContentPane().add(mob);
        mob.setBounds(370, 200, 140, 30);
        getContentPane().add(branch);
        branch.setBounds(370, 260, 140, 30);
        getContentPane().add(user_name);
        user_name.setBounds(370, 320, 140, 30);
        getContentPane().add(pass);
        pass.setBounds(370, 380, 140, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Insert Data");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 0, 120, 40);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(410, 500, 72, 23);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 380, 110, 20);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 90, 110, 20);

        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 150, 110, 20);

        jLabel5.setText("Mobile");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 210, 110, 20);

        jLabel6.setText("Branch");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 270, 110, 20);

        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 330, 110, 20);

        next.setText("Next");
        getContentPane().add(next);
        next.setBounds(180, 500, 72, 23);

        lb1.setBackground(new java.awt.Color(255, 0, 0));
        lb1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb1.setToolTipText("");
        getContentPane().add(lb1);
        lb1.setBounds(230, 40, 260, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        //Taking Data from this frame and then passing it to the DTO frame for getter and setter then calling saveData method and passing the 
        //DTO's object
        StudentRegDAO data = new StudentRegDAO();
        StudentRegDTO reg = new StudentRegDTO();
        reg.setSname(sname.getText());
        reg.setSadd(sadd.getText());
        reg.setMob(Integer.parseInt(mob.getText()));
        reg.setBranch(branch.getText());
        reg.setUnm(user_name.getText());
        
        String pw1 = new String(pass.getPassword());
        reg.setPass(pw1);
        
        int x = data.saveData(reg);
        lb1.setText(x+" row affected");
        
        sname.setText("");
        sadd.setText("");
        mob.setText("");
        branch.setText("");
        user_name.setText("");
        pass.setText("");
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestApplicationInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestApplicationInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestApplicationInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestApplicationInsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestApplicationInsertForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField mob;
    private javax.swing.JButton next;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField sadd;
    private javax.swing.JButton save;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
